name: Android Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' # JDK 17 stabil untuk compile targetSdk 33
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Sign APK Manually
      run: |
        # 1. Dekode keystore dari GitHub Secrets
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
        
        # 2. Cari lokasi Build Tools versi 33 ke atas secara otomatis
        # Ini akan mencari folder build-tools yang ada di runner GitHub
        BUILD_TOOLS_PATH=$(ls -d $ANDROID_SDK_ROOT/build-tools/3* | tail -1)
        echo "Menggunakan Build Tools dari: $BUILD_TOOLS_PATH"
        
        # 3. Proses Signing
        $BUILD_TOOLS_PATH/apksigner sign \
          --ks release.keystore \
          --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
          --ks-pass pass:"${{ secrets.KEY_PASSWORD }}" \
          --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
          --out app/build/outputs/apk/release/newsapp-release-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload APK Result
      uses: actions/upload-artifact@v4
      with:
        name: NewsApp-Signed-APK
        path: app/build/outputs/apk/release/newsapp-release-signed.apk
